ci:
  skip: [typescript-check]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-vcs-permalinks
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: 'package\.json$'
        additional_dependencies:
          - prettier@latest
          - "@kjanat/prettier-config@latest"
  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.4.16"
    hooks:
      - id: biome-check
  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: v1.1.1
    hooks:
      - id: tombi-format
      - id: tombi-lint
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript type check
        entry: bun run typecheck
        language: system
        # types: [ts]
        pass_filenames: false
